### ISSUE TITLE
successURL и failURL

### ISSUE THREAD

**Issue by mrnull** [yandex-money/yandex-money-cms-wp-woocomerce#1]
Подскажите пожалуйста, что необходимо указать в качестве successURL и failURL при выборе способа подключения к Яндекс Кассе?

**Comment by ikarmanov** [comment]
Добрый день, mrnull.

На данный момент адреса successURL и failURL должны иметь постоянные значения. Например, можно указать главную страницу Вашего магазина.

**Comment by polozov** [comment]
mrnull, здравствуйте! Вам еще нужна консультация по данному модулю или issue можно закрывать?
