### ISSUE TITLE
Иногда не перекидывает на страницу яндекса

### ISSUE THREAD

**Issue by ygennew** [yandex-money/yandex-money-cms-wp-woocomerce#11]
Несколько раз в неделю клиенты жалуются на то, что не перекидывает на страницу оплаты яндекса, а "зависает" на странице "сейчас вы будете переадресованы". Обновление не помогает - только копирование адреса страницы и открытии в новом окне. 

Сам ловил этот "баг" только один раз, не додумался header прочитать. Сейчас пока не получается отловить, но клиенты все ещё жалуются периодический.

Возможно кто-то знает в чём моет быть причина? 

Версия WC:	2.2.6
Версия базы данных WC:	2.2.6
Версия WP:	3.9.1
WP Multisite Enabled:	Нет
Информация Web-сервера:	Apache/2.4.10 (Unix)
Версия PHP:	5.5.33
Версия MySQL:	5.6.28

**Comment by ikarmanov** [comment]
Добрый день.

Такая ситуация могла возникнуть из-за проблем с загрузкой изображений на сайте в момент перехода на страницу сервиса Яндекс.Кассы. Рекомендую установить [актуальную версию](https://github.com/yandex-money/yandex-money-cms-wp-woocomerce/releases) модуля и проверить устранение проблемы.
