### ISSUE TITLE
Пробелы перед <?xml...?>, вызывающие ошибку "response is not XML".

### ISSUE THREAD

**Issue by volonterx** [yandex-money/yandex-money-cms-wp-woocomerce#13]
В ответе, который отдается по адресу https://exmapleshop.com/?yandex_money=check 
Перед объявлением xml был перевод строки и несколько пробелов. Из-за этого при парсинге страницы появлялась ошибка: 

```
- Техническая ошибка на стороне магазина: response is not XML. response:
        <?xml version="1.0" encoding="UTF-8"?>
                        <checkOrderResponse performedDatetime="2016-05-17T06:24:59+00:00" code="0" 

```

Предлагаю исправление: 
https://github.com/yandex-money/yandex-money-cms-wp-woocomerce/pull/12

В нашем магазине используется WooCommerce + Storefront. Но в самом коде дописывали функции и изменяли дизайн; я не смог понять, откуда перед ответом появлялись пробелы и перевод строки.

На всякий случай, список плагинов с версиями для тех, у которых версия не последняя. 
- Hide Title
- Jetpack от WordPress.com (3.8.2)
- Landing Pages (2.1.1)
- Regenerate post permalinks
- Storefront Designer
- Storefront Product Pagination
- Storefront WooCommerce Customiser
- WooCommerce Customizer (2.1.1)
- WooCommerce Product Details Customiser
- WooThemes Helper
- WP Database Backup (3.9.2)
- yandexmoney_wp_woocommerce
- YITH Essential Kit for WooCommerce #1 (1.1.15)
- Yoast SEO (3.0.7)
- Магазин WooCommerce

**Comment by ikarmanov** [comment]
Спасибо за исправление. 
Скоро его одобрим и включим в новую версию модуля.

**Comment by ikarmanov** [comment]
Новая версия с изменениями опубликована.
