### ISSUE TITLE
This XML file does not appear to have any style information associated with it. The document tree is shown below.

### ISSUE THREAD

**Issue by madsinner** [yandex-money/yandex-money-cms-wp-woocomerce#15]
При проверки вывода https://mydomain.ru/?yandex_money=check выходит следующая информация

**This XML file does not appear to have any style information associated with it. The document tree is shown below.
Response performedDatetime="2016-06-14T11:15:21+00:00" code="1" invoiceId="" shopId="0" techMessage="bad md5"**

Данные сайта:
Версия WC:		2.5.5
Версия WP:		4.5.2
Версия Yandex.Money – 2.3.0.1 + исправления из ветки https://github.com/yandex-money/yandex-money-cms-wp-woocomerce/issues/13

Прошу помощи.
P.S. 
shopid заменил на 0, в оригинале id показывает верно

**Comment by ikarmanov** [comment]
Добрый день.

Адрес checkUrl/avisoUrl (https://mydomain.ru/?yandex_money=check) предназначен для обмена служебной информацией между сервисом Яндекс.Касса и нашим модулем магазина. При переходе по адресу через браузер выводимая информация может искажаться, т.к. модуль "ожидает" данные от Яндекс.Кассы, а не от браузера пользователя/администратора магазина.

Совершите оплату по собственному заказу и убедитесь, что модуль работает и статус заказа изменился.

**Comment by madsinner** [comment]
Добрый день.

Это все понятно.
Только что пытался оплатить… выходит техническая ошибка, деньги снимаются и через пару минут возвращаются… заказ не оплачивается…
Проблема в том, что другие сервисы (робокасса в частности )без проблем принимает post запросы как по http так и по https
а вот ваш модуль принимает только почему то по http, а по https шлет в 403 ((

Ковыряем сервер. Открыли уже все что только можно, без результата…

Запрос от вас случаем не в TLSv1.2 ?

Еще вопрос, возможна смена алгоритма расчета хэша с md5 на sha256 или (судя по коду) это не предусмотрено?

С Уважением
Лемешев В.В.
моб. 89090418994

**Comment by ikarmanov** [comment]
> а вот ваш модуль принимает только почему то по http, а по https шлет в 403 ((

В модуле нет кода, который бы возвращал код 403 при POST-запросе. Попробуйте самостоятельно оправить POST-запрос с помощью cURL `curl -kvd 'customerNumber=..&shopId=..' https://mydomain.ru/?yandex_money=check`

>Запрос от вас случаем не в TLSv1.2 ?

Лучше уточнить это у наших техников, которые отправляли Вам настройки для работы с Яндекс.Кассой.

>возможна смена алгоритма расчета хэша с md5 на sha256

Изменить нельзя.

**Comment by madsinner** [comment]
Благодарю за разъяснения

Просто уже не знаем куда копать… так как на глазах рабочий пример робокассы, где post проходит без проблем(((
В ближайшие дни будем обновлять apache до 2.4 и с нуля писать все конфиги, как раз получим поддержку тлс всех и попробуем заново тестировать

Самостоятельно post отправляем, проверяя каждое изменение конфигурации, пока без результата 

Еще вопрос…  тестировать плагин лучше в оригинальной версии или с исправлениями из https://github.com/yandex-money/yandex-money-cms-wp-woocomerce/pull/12 <https://github.com/yandex-money/yandex-money-cms-wp-woocomerce/pull/12>

Спасибо, будем работать. 


С Уважением
Лемешев В.В.
моб. 89090418994

**Comment by ikarmanov** [comment]
>Самостоятельно post отправляем, проверяя каждое изменение конфигурации, пока без результата

Т.е. код ответа `200 OK` или `403`? 

>Еще вопрос… тестировать плагин лучше в оригинальной версии или с исправлениями из #12 <#12>

С исправлением можно исключить возможные проблемы с выводом ответа, но Вам нужно разобраться с кодом ответа веб-сервера. 

>В ближайшие дни будем обновлять apache до 2.4 и с нуля писать все конфиги, как раз получим поддержку тлс всех и попробуем заново тестировать
>Спасибо, будем работать.

Если проблема повторится, то попросите наших техников добавить рассылку cms@ в переписку с Вами - будем вместе искать причину.

**Comment by madsinner** [comment]
Здравствуйте.

Проблему решили.
Помогла принудительная привязка хоста на 443 порт в конфигурации Apache (использование TLSv1.2 не обязательно)

NameVirtualHost fan-house.ru:443

Платеж проверили - успешно.

Спасибо Большое за помощь.

С Уважением
Лемешев В.В.
моб. 89090418994
