### ISSUE TITLE
Модуль отдает вместо ответа не XML

### ISSUE THREAD

**Issue by Dimkox** [yandex-money/yandex-money-cms-wp-woocomerce#16]
Добрый день!
Платежи неуспешны, так как магазин на наш запрос отвечает не по протоколу.
Код ответа:
[2016-09-19T14:59:24.778+0300] WARN [http-nio-0.0.0.0-8001-exec-58] [47517.SHID] [Cstw5602QSU=.5e1b] [1f71e6a4-0009-5000-8000-000014c836ef] [AbstractIPWPaymentHandler] - Техническая ошибка на стороне магазин
а: response is not XML. response:<?xml version="1.0" encoding="UTF-8"?>
                        <checkOrderResponse performedDatetime="2016-09-19T11:59:24+00:00" code="0" invoiceId="2000509845743" shopId="47517" techMessage="completed"/><div style="position:absolute;top:-9999px;l
eft:-9999px;disply:none;">......
ru.yamoney.calypso.shops.adapters.ShopErrorException: response is not XML. response:<?xml version="1.0" encoding="UTF-8"?>
                        <checkOrderResponse performedDatetime="2016-09-19T11:59:24+00:00" code="0" invoiceId="2000509845743" shopId="47517" techMessage="completed"/><div style="position:absolute;top:-9999px;l
eft:-9999px;disply:none;">......

Уточните, пожалуйста, вы используете наш модуль оплаты? Если да, то пришлите, пожалуйста, временный доступ в административную панель вашего сайта для проверки параметров модуля оплаты.

Бекк Максим
Группа сопровождения контрагентов
ООО НКО "Яндекс.Деньги"

**Comment by ikarmanov** [comment]
Добрый день.

Какая версия модуля установлена? Файлы модуля подвергались изменениям?

**Comment by Dimkox** [comment]
2.3.2, прилетевшая из репозитория Wordpress

**Comment by Dimkox** [comment]
ничего мы там не трогаем от греха подальше

**Comment by Dimkox** [comment]
Появилась версия 2.3.3 в репозитории WP https://wordpress.org/plugins/yandexkassa/
Это,я  надеюсь, рабочая версия?
Почему её нет здесь?

**Comment by ikarmanov** [comment]
Добрый день.

Публикация модуля по адресу https://wordpress.org/plugins/yandexkassa/ является для нас приоритетной, т.к. этот канал является более удобным для пользователей CMS Wordpress.
