### ISSUE TITLE
Замечания в дебаг-режиме

### ISSUE THREAD

**Issue by lemonleks** [yandex-money/yandex-money-cms-wp-woocomerce#4]
Магазин подключен в боевой режим, платежи проводятся успешно любыми способами, но в дебаг-режиме выводятся замечания:

Notice: Undefined index: yandex_money in /home/l/lemonl6a/odeyalko39.ru/public_html/wp-content/plugins/yandex_money/yandex_money.php on line 110 

Notice: woocommerce_recently_viewed cookie cannot be set - headers already sent by /home/l/lemonl6a/odeyalko39.ru/public_html/wp-content/plugins/yandex_money/yandex_money.php on line 110 in /home/l/lemonl6a/odeyalko39.ru/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 553

**Comment by ikarmanov** [comment]
Проблема с предупреждениями в отладочном режиме устранена. Рекомендуем обновить платежный модуль.
