### ISSUE TITLE
Поддержка Яндекс.Денег

### ISSUE THREAD

**Issue by cyxou** [yandex-money/yandex-money-cms-wp-woocomerce#6]
Видел новость о том, что с 27 октября для профессиональных аккаунтов Яндекс.Деньги появляется возможность принимать оплату посредством всех доступных платежных систем. Есть ли возможность настроить плагин на работу с Яндекс.Деньгами?

**Comment by ikarmanov** [comment]
Добрый день.

Данный модуль работает только с сервисом Яндекс.Касса.
