### ISSUE TITLE
Не работает на WP 4.4.2

### ISSUE THREAD

**Issue by jacky12345** [yandex-money/yandex-money-cms-wp-woocomerce#8]
Не работает на WP 4.4.2. После активации Вашего модуля, в меню плагина "Woocomerce
 - Настройки - Платежи" пункт Яндекс.Деньги не появился. Вот скриншот http://savepic.org/8165989.jpg

**Comment by ikarmanov** [comment]
Добрый день.

Прошу Вас загрузить [архив с модулем](https://github.com/yandex-money/yandex-money-cms-wp-woocomerce/blob/master/yandex_money.zip?raw=true) еще раз и повторить установку.

**Comment by jacky12345** [comment]
Спасибо за ответ! Но за это время подключил уже Единый Кошелёк. А у них есть ЯДеньги
