### ISSUE TITLE
кавычка

### ISSUE THREAD

**Issue by gotmeth** [yandex-money/yandex-money-cms-wp-woocomerce#9]
yandex_money.php:207

> `<td><input type="checkbox" name="ym_Demo" <?php echo get_option('ym_Demo')=='on'?'checked="checked"':''; ?>" /></td>`

`<td><input type="checkbox" name="ym_Demo" <?php echo get_option('ym_Demo')=='on'?'checked="checked"':''; ?> /></td>`

**Comment by ikarmanov** [comment]
Добрый день.

Спасибо. [Строку](https://github.com/yandex-money/yandex-money-cms-wp-woocomerce/blob/master/yandex_money/yandex_money.php#L207) исправим.
